### ISSUE TITLE
Start from Command Line

### ISSUE THREAD

**Issue by taylorn-ai** [CamW/shrew-reconnect#1]
Is there any ability to start from command line (so as to be started as a service)?
E.g.
`./ShrewReconnect.exe /connect`

**Comment by CamW** [comment]
There is not currently a command-line option to start immediately, I've marked this as an enhancement  and will implement it in a future release.

**Comment by CamW** [comment]
I've added a checkbox on the main screen which allows you to configure connect on startup. Take a look at the new version.
