### ISSUE TITLE
two issues

### ISSUE THREAD

**Issue by dshleg** [CamW/shrew-reconnect#3]
os : windows 10 x64 anniversary update
1. first connect ok, when reconnect unable to load site config
2. many reconnect crashes "shrew vpn reconnect"

**Comment by CamW** [comment]
I wasn't able to reproduce this issue, however, I did find and fix a bug which may have caused this. Please try out the latest version (1.0.7) and let me know if the problem persists. If it does persist, perhaps you could provide a screenshot of what you're seeing?

**Comment by CamW** [comment]
No response from OP and not able to reproduce.
