### ISSUE TITLE
Cannot download installer

### ISSUE THREAD

**Issue by EnnoKarsten** [CamW/shrew-reconnect#4]
Hi Cameron,
I cannot download the installer from http://www.waldron.co.za/downloads/installers/ShrewReconnectLatest64.msi
Can you please let me know what I am doing wrong or how I can download it?
I get a "Connection refused" error.
Many thanks and best regards,
Enno

**Comment by CamW** [comment]
Apologies, the server was down. Please try again.

**Comment by EnnoKarsten** [comment]
Hi Cameron,
Thanks a lot for this super quick reply and problem resolution.
Download has been working now.
Best regards,
Enno
