### ISSUE TITLE
Item for read.me: running with limited user rights

### ISSUE THREAD

**Issue by Milmoor** [CamW/shrew-reconnect#7]
Shrew reconnect needs administrative privileges. If you start it, it therefore will ask for admin credentials. It will look for the .vpn file in the roaming folder of the used administrative user. If you elevate from a limited account, this won't be the current user. This is confusing since Shrew does store it's .vpn in the current user. You need to either copy the .vpn to the administrative user, or (quite probably, but untested) do the configuration of Shrew elevated as well.

Please add this to the documentation, it can save someone else a bit of time. Thank you for your tool for taming the Shrew, it's very useful.

**Comment by CamW** [comment]
Thank you for the issue report, I've added it to the readme under connecting
